"""
cli_helpful_type_hints.py

Generates jinja-lsp context stubs for every .prompt model so that VS Code
(via the jinja-lsp extension) can provide autocomplete and type checking
inside Jinja templates.

For each model a stub is written to  .pbt/gen/<model>_context.py  that:
  - imports the validation class for each upstream dependency (if one exists)
  - declares a typed variable whose name matches the upstream model name
  - declares a ``this`` variable typed to the model's own validation class

jinja-lsp reads top-level variable annotations from Python files listed in
``pyproject.toml``'s ``[tool.jinja-lsp] backend`` list.  This module also
ensures that section exists so the LSP finds both the raw validation/ folder
and the generated .pbt/gen/ folder.

Validation files that contain only a ``validate()`` function and no class
definition are silently skipped — the stub is still generated so jinja-lsp
doesn't lose track of the file; it just won't carry type information for
that particular variable.

Usage
-----
Called automatically by the ``pbt type-hints`` CLI command:

    pbt type-hints
    pbt type-hints --models-dir models --validation-dir validation

Or imported directly:

    from cli_helpful_type_hints import generate_stubs, update_pyproject_toml
    written = generate_stubs("models", "validation")
    update_pyproject_toml("models", "validation")
"""

from __future__ import annotations

import ast
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_GEN_DIR = ".pbt/gen"

_HEADER = """\
# Auto-generated by `pbt type-hints` — do not edit by hand.
# Re-run `pbt type-hints` to refresh after changing .prompt files or
# validation classes.

"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _first_class_in_file(py_path: Path) -> str | None:
    """
    Return the name of the first class defined at module level in *py_path*.
    Returns None if the file has no class definitions or cannot be parsed.
    """
    try:
        source = py_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(py_path))
    except (SyntaxError, OSError):
        return None

    for node in ast.iter_child_nodes(tree):   # top-level only
        if isinstance(node, ast.ClassDef):
            return node.name
    return None


def _module_path(validation_dir: str, stem: str) -> str:
    """Convert a filesystem path like 'validation' + 'article' → 'validation.article'."""
    return f"{validation_dir.replace('/', '.').strip('.')}.{stem}"


# ---------------------------------------------------------------------------
# Core: stub generation
# ---------------------------------------------------------------------------

def generate_stubs(
    models_dir: str = "models",
    validation_dir: str = "validation",
    gen_dir: str = _GEN_DIR,
) -> list[str]:
    """
    Walk *models_dir*, build the dependency graph, and emit one
    ``<model>_context.py`` stub per model into *gen_dir*.

    Returns a list of file paths that were written.

    Raises
    ------
    FileNotFoundError
        Propagated from ``load_models`` when *models_dir* does not exist or
        contains no prompt files.
    """
    # Lazy import so this module can be imported without the full pbt package
    # installed in contexts where only graph.py is on sys.path.
    from pbt.executor.graph import load_models

    models = load_models(models_dir)
    val_dir = Path(validation_dir)
    out_dir = Path(gen_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # jinja-lsp needs the directory to be a Python package
    init_py = out_dir / "__init__.py"
    if not init_py.exists():
        init_py.write_text("", encoding="utf-8")

    written: list[str] = []

    for model_name, model in models.items():
        import_lines: list[str] = []
        var_lines: list[str] = []

        # --- upstream dependencies -------------------------------------------
        for dep in model.depends_on:
            val_file = val_dir / f"{dep}.py"
            if not val_file.exists():
                continue
            cls = _first_class_in_file(val_file)
            if cls is None:
                continue
            import_lines.append(
                f"from {_module_path(validation_dir, dep)} import {cls}"
            )
            var_lines.append(
                f"{dep}: {cls} = None  # output of the '{dep}' model"
            )

        # --- own validation class → ``this`` ---------------------------------
        own_file = val_dir / f"{model_name}.py"
        if own_file.exists():
            cls = _first_class_in_file(own_file)
            if cls is not None:
                import_lines.append(
                    f"from {_module_path(validation_dir, model_name)} import {cls}"
                )
                var_lines.append(
                    f"this: {cls} = None  # output schema of this model"
                )

        # --- assemble stub file ----------------------------------------------
        chunks: list[str] = [_HEADER]

        if import_lines:
            chunks.extend(f"{line}\n" for line in import_lines)
            chunks.append("\n")
            chunks.extend(f"{line}\n" for line in var_lines)
        else:
            chunks.append(
                "# No typed validation classes found for this model's dependencies.\n"
                "# Add a class to the matching validation/*.py file to enable\n"
                "# autocomplete for that variable inside this template.\n"
            )

        stub_path = out_dir / f"{model_name}_context.py"
        stub_path.write_text("".join(chunks), encoding="utf-8")
        written.append(str(stub_path))

    return written


# ---------------------------------------------------------------------------
# pyproject.toml: jinja-lsp section
# ---------------------------------------------------------------------------

def update_pyproject_toml(
    models_dir: str = "models",
    validation_dir: str = "validation",
    gen_dir: str = _GEN_DIR,
    pyproject_path: str = "pyproject.toml",
) -> bool:
    """
    Ensure ``pyproject.toml`` contains a ``[tool.jinja-lsp]`` section.

    If the section already exists it is left completely untouched so user
    customisations are preserved.  Returns True if the file was modified,
    False if it already had the section.
    """
    path = Path(pyproject_path)
    content = path.read_text(encoding="utf-8") if path.exists() else ""

    if "[tool.jinja-lsp]" in content:
        return False  # already configured

    block = (
        "\n[tool.jinja-lsp]\n"
        f'templates = "./{models_dir}"\n'
        f'backend = ["./{validation_dir}", "./{gen_dir}"]\n'
        'lang = "python"\n'
    )
    path.write_text(content + block, encoding="utf-8")
    return True
