"""
Shared fixtures for pbt CLI integration tests.

All tests run pbt as a real subprocess so they exercise the installed
entry-point end-to-end.  A stub client.py is injected into every test
project so no real LLM API key is required.
"""

import subprocess
import textwrap
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Stub LLM client
# ---------------------------------------------------------------------------

# Returns a response long enough to pass validation/article.py
# (>= 200 chars, contains a "#" markdown header).
STUB_CLIENT_PY = textwrap.dedent("""\
    import json

    def llm_call(prompt: str, files: list | None = None, config: dict | None = None) -> str:
        # Test prompts ask for {"results": "pass"} or {"results": "fail"}
        if '"results": "pass"' in prompt or '"results":"pass"' in prompt:
            return json.dumps({"results": "pass"})
        if (config or {}).get("output_format") == "json":
            return json.dumps({
                "summaries": [{
                    "title": "Mock Title",
                    "summary": "Mock summary sentence one. Mock summary sentence two.",
                    "key_points": ["Point one", "Point two", "Point three"],
                }]
            })
        return (
            "# Mock Article Title\\n\\n"
            "This is a mock LLM response generated by the pbt test suite. "
            "It is intentionally long enough to satisfy the article validation "
            "rule that requires at least 200 characters and a markdown header. "
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
            "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        )
""")

STUB_CLIENT_JSON_PY = textwrap.dedent("""\
    import json

    def llm_call(prompt: str) -> str:
        return json.dumps({"title": "Mock Title", "summary": "Mock summary."})
""")

# Stub that accepts files kwarg and echoes back how many bytes were read from each file.
STUB_CLIENT_FILES_PY = textwrap.dedent("""\
    def llm_call(prompt: str, files: list | None = None, config: dict | None = None) -> str:
        file_sizes = [len(f.read()) for f in (files or [])]
        sizes_str = ", ".join(str(s) for s in file_sizes)
        return (
            "# Mock Response\\n\\n"
            f"Received {len(file_sizes)} file(s) with sizes: [{sizes_str}]. "
            "This is a mock LLM response generated by the pbt test suite. "
            "It is intentionally long enough to satisfy the article validation "
            "rule that requires at least 200 characters and a markdown header. "
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        )
""")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run_pbt(*args: str, cwd: Path, check: bool = True, env=None) -> subprocess.CompletedProcess:
    """Run `pbt <args>` in *cwd*, return the CompletedProcess."""
    return subprocess.run(
        ["pbt", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=check,
        env=env,
    )


def init_project(tmp_path: Path, provider: str = "gemini", name: str = "proj") -> Path:
    """
    Run `pbt init` in *tmp_path* and replace the scaffolded client.py with
    the stub so tests never hit a real LLM.  Returns the project root.
    """
    run_pbt("init", name, "--provider", provider, cwd=tmp_path)
    proj = tmp_path / name
    (proj / "client.py").write_text(STUB_CLIENT_PY, encoding="utf-8")
    return proj


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def proj(tmp_path: Path) -> Path:
    """A freshly initialised pbt project with the stub LLM client."""
    return init_project(tmp_path)
