"""
pbt/cli/type_hints.py

Generates jinja-lsp context stubs for every .prompt model so that VS Code
(via the jinja-lsp extension) can provide autocomplete and type checking
inside Jinja templates.

For each model a stub is written to  .pbt/gen/<model>_context.py  that:
  - imports the validation class for each upstream dependency (if one exists)
  - declares a typed variable whose name matches the upstream model name
  - declares a ``this`` variable typed to the model's own validation class

jinja-lsp reads top-level variable annotations from Python files listed in
``pyproject.toml``'s ``[tool.jinja-lsp] backend`` list.  This module also
ensures that section exists so the LSP finds both the raw validation/ folder
and the generated .pbt/gen/ folder.

Validation files that contain only a ``validate()`` function and no class
definition are silently skipped — the stub is still generated so jinja-lsp
doesn't lose track of the file; it just won't carry type information for
that particular variable.

Usage
-----
Called automatically by the ``pbt type-hints`` CLI command:

    pbt type-hints
    pbt type-hints --models-dir models --validation-dir validation

Or imported directly:

    from pbt.cli.type_hints import generate_stubs, update_pyproject_toml
    written = generate_stubs("validation")
    update_pyproject_toml("validation")
"""

from __future__ import annotations

import ast
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_GEN_DIR = ".pbt/gen"

_HEADER = """\
# Auto-generated by `pbt type-hints` — do not edit by hand.
# Re-run `pbt type-hints` to refresh after changing .prompt files or
# validation classes.
from __future__ import annotations
from typing import Protocol, overload, Any, Literal

"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _validate_return_class(py_path: Path) -> str | None:
    """
    Return the class name declared as the return type of the top-level
    ``validate()`` function in *py_path*.

    Handles simple annotations and unions (``X | False``, ``X | None``,
    ``Union[X, ...]``).  Ignores primitive/opaque types such as ``Any``,
    ``bool``, ``str``, ``dict``, and ``list``.  Falls back to the first
    class *defined* in the file when no useful annotation is found.

    Returns None if nothing useful can be extracted or the file cannot be
    parsed.
    """
    _OPAQUE = {"Any", "bool", "str", "int", "float", "dict", "list", "None", "False"}

    def _extract_name(node: ast.expr) -> str | None:
        """Pull a single useful class name out of an annotation AST node."""
        if isinstance(node, ast.Name):
            return None if node.id in _OPAQUE else node.id
        if isinstance(node, ast.Constant):
            # Literal[False] / None as a constant
            return None
        if isinstance(node, ast.Attribute):
            return node.attr if node.attr not in _OPAQUE else None
        # X | Y  (Python 3.10+ union syntax)
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
            return _extract_name(node.left) or _extract_name(node.right)
        # Union[X, Y] / Optional[X] / Literal[False]
        if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
            if node.value.id in ("Union", "Optional"):
                elts = (
                    node.slice.elts
                    if isinstance(node.slice, ast.Tuple)
                    else [node.slice]
                )
                for elt in elts:
                    name = _extract_name(elt)
                    if name:
                        return name
        return None

    try:
        source = py_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(py_path))
    except (SyntaxError, OSError):
        return None

    first_class: str | None = None
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and first_class is None:
            first_class = node.name
        if (
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == "validate"
            and node.returns is not None
        ):
            name = _extract_name(node.returns)
            if name:
                return name

    return first_class


def _module_path(validation_dir: str, stem: str) -> str:
    """Convert a filesystem path like 'validation' + 'article' → 'validation.article'."""
    return f"{validation_dir.replace('/', '.').strip('.')}.{stem}"


# ---------------------------------------------------------------------------
# Core: stub generation
# ---------------------------------------------------------------------------

def generate_stubs(
    validation_dir: str = "validation",
    gen_dir: str = _GEN_DIR,
) -> list[str]:
    """
    Scan *validation_dir* for dataclass definitions and emit a single
    ``ref.py`` stub into *gen_dir* that types the ``ref()`` Jinja global.

    Returns a list of file paths that were written.
    """
    val_dir = Path(validation_dir)
    out_dir = Path(gen_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Collect (stem → class_name) for every validation file that has a class
    dep_classes: dict[str, str] = {}
    for val_file in sorted(val_dir.glob("*.py")):
        cls = _validate_return_class(val_file)
        if cls is not None:
            dep_classes[val_file.stem] = cls

    chunks: list[str] = [_HEADER]

    if dep_classes:
        for stem, cls in dep_classes.items():
            chunks.append(f"from {_module_path(validation_dir, stem)} import {cls}\n")
        chunks.append("\n")
        names_literal = ", ".join(f"'{s}'" for s in dep_classes)
        chunks.append(f"ModelNames = Literal[{names_literal}]\n\n")
        chunks.append("class _Ref(Protocol):\n")
        for stem, cls in dep_classes.items():
            chunks.append(f"    @overload\n")
            chunks.append(f"    def __call__(self, name: Literal['{stem}']) -> {cls}: ...\n")
        chunks.append(f"    @overload\n")
        chunks.append(f"    def __call__(self, name: str) -> Any: ...\n")
        chunks.append("\n")
        chunks.append("ref: _Ref\n")
    else:
        chunks.append(
            "# No dataclass definitions found in validation/.\n"
            "# Add a dataclass to a validation/*.py file to enable\n"
            "# ref() autocomplete inside .prompt templates.\n"
        )

    stub_path = out_dir / "ref.py"
    stub_path.write_text("".join(chunks), encoding="utf-8")
    return [str(stub_path)]


# ---------------------------------------------------------------------------
# pyproject.toml: jinja-lsp section
# ---------------------------------------------------------------------------

def update_pyproject_toml(
    validation_dir: str = "validation",
    gen_dir: str = _GEN_DIR,
    pyproject_path: str = "pyproject.toml",
) -> bool:
    """
    Ensure ``pyproject.toml`` contains a ``[tool.jinja-lsp]`` section.

    If the section already exists it is left completely untouched so user
    customisations are preserved.  Returns True if the file was modified,
    False if it already had the section.
    """
    path = Path(pyproject_path)
    content = path.read_text(encoding="utf-8") if path.exists() else ""

    if "[tool.jinja-lsp]" in content:
        return False  # already configured

    block = (
        "\n[tool.jinja-lsp]\n"
        'templates = "./models"\n'
        f'backend = ["./{validation_dir}", "./{gen_dir}"]\n'
        'lang = "python"\n'
    )
    path.write_text(content + block, encoding="utf-8")
    return True


# ---------------------------------------------------------------------------
# CLI command — registered onto the main Click group from cli/__init__.py
# ---------------------------------------------------------------------------

def register_command(main) -> None:
    """Attach the `pbt type-hints` command to *main* Click group."""
    import click

    @main.command("type-hints")
    @click.option("--validation-dir", default="validation", show_default=True,
                  help="Directory containing per-model validation Python files.")
    @click.option("--gen-dir", default=".pbt/gen", show_default=True,
                  help="Output directory for generated context stubs.")
    @click.option("--pyproject", "pyproject_path", default="pyproject.toml", show_default=True,
                  help="Path to pyproject.toml to update with jinja-lsp config.")
    def type_hints(validation_dir: str, gen_dir: str, pyproject_path: str) -> None:
        """Generate jinja-lsp context stubs for autocomplete in .prompt templates."""
        from rich.console import Console
        console = Console()

        written = generate_stubs(validation_dir, gen_dir)

        for path in written:
            console.print(f"  [green]wrote[/green]  {path}")

        toml_updated = update_pyproject_toml(validation_dir, gen_dir, pyproject_path)
        if toml_updated:
            console.print(f"  [green]wrote[/green]  {pyproject_path}  [dim](added [tool.jinja-lsp] section)[/dim]")
        else:
            console.print(f"  [dim]skipped[/dim] {pyproject_path}  [dim]([tool.jinja-lsp] already present)[/dim]")

        console.print(
            f"\n[bold]Done.[/bold] Install the [cyan]jinja-lsp[/cyan] VS Code extension "
            f"to activate autocomplete in your .prompt files."
        )
